### ISSUE TITLE
equistore.__version__

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/equistore#102]
Currently, we have a version info when installing equistore via pip etc. However, there is no `__version__` attribute when using equistore from the Python interpreter.

We should add this attribute. `__version__` helps a lot with debugging production code, especially when using rascaline together equistore which could lead to some weird version clash behavior.

A quick and dirty solution is the following. We are pulling the version from the rust code using 

https://github.com/lab-cosmo/equistore/blob/e65cd07d2f0d5aefa41a7b2beade835b9b1dc03b/setup.py#L91-L98

in `setup.py`. During this step we can write a `version.py` file to the source and import this in our `__init__.py`.

Another maybe cleaner  would be providing a version string from `rust` over `c` to `Python`.

**Comment by Luthaf** [comment]
Both options (create a `version.py` file) and get the version of a rust function are implemented in #85. We can then compare the two of them with one another to ensure the Python code loads a shared library it can understand.

**Comment by PicoCentauri** [comment]
Nice. So we close this once #84 is merged.
