### ISSUE TITLE
Broadcasted TensorMap/TensorBlock x scalar operations (add, minus, multiplication, division)

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/equistore#118]
Because issue #101 is too large as one feature request, I split it up into chunks. This is the first chunk.

So we have this use case
```python
# A is TensorMap
a = 10
A = add(A, a)
```

lets say we use an add function for this, then it would look like

```python
def add(A, a):
    _A = copy(A)
    for key, block in _A.blocks():
        block.values += a
        for key, grad in block.gradients():
            grad.data += a
    return _A
```

### QUESTION/PROBLEM I think one conceptual problem is how should we differ between a operation considering gradient and just broadcasting operation as shown above

So the above example would be fully broadcasting operation and the below one would recognize the gradients
```python
def add(A, a):
    _A = copy(A)
    for key, block in _A.blocks():
        block.values += a
        # no operation applied on gradients since ∇(A+a) = ∇A
    return _A
```

Maybe this can be solved with an additional argument `gradient_operation`

```python
def add(A, a, gradient_operation=False):
    _A = copy(A)
    for key, block in A.blocks():
        block.values += a
        if not(gradient_operation):
            for key, grad in block.gradients():
                grad.data += a
    return _A
```

### QUESTION/PROBLEM how to do inplace operations?

The above ignores inplace operations, which would be required at some point, but I don't fully understand how numpy's inplace operation work
```python
A += 10 # seems to be inplace
B = A + 10 # not this inplace
A = A + 10 # is this inplace? I think not
np.add(A, 1, out= A) # seems to also not be inplace, but works different than the above ones
```
in the end we would like something as `add(A, scalar, out=A)`, to be inplace.

**Comment by Luthaf** [comment]
The "just broadcasting operation" makes no sense, because it result in a TensorMap where the `gradients` are no longer the actual gradients of the `values`, breaking an invariant of TensorMap. I don't think we should provide these, except if you have a really compelling case where you need them?

> The above ignores inplace operations

All of your examples are doing inplace operations, modifying the input tensormap instead of making a copy.

**Comment by DavideTisi** [comment]
So, I think that breaking the relation between values and gradient is a bit against the main idea of equistore Which keep together some quantities and its gradient. 
To answer your first question the idea for doing that operation would be to create a new TensorBlock equal to the gradient block of `A` (let's call it `gA`) and then do the add operation on `gA` in this way you have 2 blocks which are not dependent to each other anymore.

I am positive to introduce in the operations a new variable `do_gradient: bool = True`, if `True` the operation computes the gradient and give as output a new TB with the correct gradient. If `False` it do not compute the gradient and the function gives as result a TB with no gradient associated. This might be useful in particular for non-linear operations like std and variance where the derivative implies a lot of calculations and we often do not want the derivative of `std`, for example.

**Comment by Luthaf** [comment]
> I am positive to introduce in the operations a new variable do_gradient: bool = True, if True the operation computes the gradient and give as output a new TB with the correct gradient.

That would work for me! 

> The same result can be achieved by computing also the gradient then using ops.remove_gradients but for large block the computation of the derivative might be costly.

a less costly but still not great solution (since the values can be big, and this results in a copy) would be to remove the gradients before the operation.

**Comment by DavideTisi** [comment]
I thought a bit about this issue and one idea is to have a function that separates gradients and the TensorBlock. One Draft of the idea is in #123, I think it is still a bit in contrast with the spirit of equistore and the binding between values and gradients but at least here you clearly break this bond and you do not have a ``TensorBlock`` with the attached gradients which are "out-of-sync".  what do you think?

**Comment by agoscinski** [comment]
>The "just broadcasting operation" makes no sense, because it result in a TensorMap where the gradients are no longer the actual gradients of the values, breaking an invariant of TensorMap. I don't think we should provide these, except if you have a really compelling case where you need them?

> So, I think that breaking the relation between values and gradient is a bit against the main idea of equistore Which keep together some quantities and its gradient.

For us it makes a lot of sense to have such an option, because it removes boiler plate code. We store a lot of outputs also as TensorMap like the error, because we want the error for each TensorBlock, and for the values and each gradient. At this point this object does not have the actual meaning anymore, but just uses the same structure. Then we want to apply basic arithmetic operations on it to weight the errors differently. If you have a flag which is by default off, call it "unsafe_operation=False", I am okay with it. Sometimes you want give the user more flexibility with the risk of messing up stuff.

### Inplace

> All of your examples are doing inplace operations, modifying the input tensormap instead of making a copy.

You mean the python example? `B=A+10` does at a certain point a copy, I think it makes a temporary object and then does an inplace operation on this temporary object, but tracking the `__iadd__` function, I could not observe it being invoked when doing `B=A+10`. Thats why I don't understand this yet.

**Comment by Luthaf** [comment]
> For us it makes a lot of sense to have such an option, because it removes boiler plate code.

I would rather have a bit more boilerplate code than introduce another mode of operation and completely different semantics that will confuse newcomers trying to read the code (in general, I believe code should be optimized to be clear when read first, easy and short to write second). 

For errors, I can see how the error on gradients is not the gradients of the error on values and you'd want to store them in a TensorMap. My preference would be to use a different storage format, in the same vein as #123. If that's too difficult, we could compute the different arrays and manually construct the metadata to create a Frankenstein'ed TensorMap, something like 

```py
blocks = []

for block in tensor:
    error_values = some_function(block.values)
    error_gradients = {}
    for parameter, gradient in block.gradients():
        error_gradients[parameter] = error_weight * some_function(gradient)

    # TODO: build the metadata here
    error_block = TensorBlock(error_values, ...)
    error_block.add_gradient(parameter, ...)
```

If that code is isolated in a function, It should not be too bad in term of boilerplate.

> Inplace

Sorry, I missed the `_A = copy(A)` in your examples, then yes, these are indeed not inplace!

**Comment by agoscinski** [comment]
> I would rather have a bit more boilerplate code than introduce another mode of operation and completely different semantics that will confuse newcomers trying to read the code (in general, I believe code should be optimized to be clear when read first, easy and short to write second).

What if it is not in the same function (e.g. `add`), but in a separate function (e.g. `unsafe_add`), so a new user does not see this. It can be hidden in some subpackage so a new user does not need to now about.

> My preference would be to use a different storage format

I feel like for the user it is more intuitive if he/she gets it in the same format as the features. That actually allows us to be more flexible with the scorer class (per sample error, per feature error) where the meta data would be useful.

**Comment by agoscinski** [comment]
Are you okay if we add a helper function equisolve for the regularizers and see in the future how useful this is for other instances? If it is just for this one use case, I can see that adding an option here is not worth it.

**Comment by agoscinski** [comment]
I think the core of the issue has been already addressed with the current add,, the gradient compliant flag is a different issue and will be tested first in equisolve.
