### ISSUE TITLE
Operations on `Labels`, `TensorBlock`: public, privates, mixed?

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/equistore#120]
Currently, operations that act on `TensorBlock`s and `Labels` are (at least) for me inconsistently publicly available or only private i.e for TensorBlocks:

**public**: `allclose_block`, `slice_block`, ...
**pirvate**: `_join_blocks`, `_dot_block`, _solve_block, ...

and for Labels:

**public**: `unique` 
**private**: `_join_labels`

I think we should either make them consistently public or private. This also important for #116 where the idea came up that the new `unique` function does take `Labels` and not a `TensorMap`.

For a consistent user experience it might make sense that all our operations take only `TensorMaps` and we try to _hide_ Blocks and Labels under the hood.

Ideas, Opinions?

**Comment by DavideTisi** [comment]
I do not know it is a small inconsistence, but it is not huge.
I agree that the general idea is that the public operations act on ``TensorMaps``, but some might be useful for example ``all_close`` and in particular, the `_raise` version tells you where the two ``TensorMaps`` differs. But ``all_close`` tells you which block it is different, while ``all_close_block`` tells you which label or part of the block is different.

**Comment by Luthaf** [comment]
After discussion, we agreed that we can have public operations on all of the core classes (`TensorMap`, `TensorBlock` and `Label`)
