### ISSUE TITLE
Introduce a consistent and clear format for function docstrings

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/equistore#132]
Re: the ML development meeting, let's decide on a consistent format for function docstrings, using @PicoCentauri 's suggestion as a starting point. Then, once agreed, we can do an overhaul of all function docstrings, then enforce the format in subsequent PRs.

**Comment by PicoCentauri** [comment]
Thanks for pinging @jwa7. 

Our general docstring format follows the [Sphinx format](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html). Additionally, to make the docstring better readable I suggest

1. Start the description after each `:param:` or `:return:` in a new line and add an empty line between the parameter and return block.
2. Emphasize function and class parameters with a single backtick i.e  \`param\` and general variables should be double backticked .i.e.  \`\`my_variable\`\`

Below an example

```rst
ONE LINE summary sentence.
    
Extensive multi line summary of what is going in. Use single 
backticks for paramaters of the function like `width` and two ticks for
values ``67``. You can link to classes :py:class:equistore.Labels`. This
also works for other classes and functions like :py:obj:`True`.

Inline Math is also possible with :math:`\mathsf{R}`. Or as a math block.

.. math::

    \mathbf{x}' = \mathsf{R}\mathbf{x}


:param value:
    The first value of the function.
:param value:
    second parameters

:returns prev:
    the result of the calculation

:raises ValueError:
    if value is not a float

Examples
--------

This is a first example
>>> from equistore import func
>>> func(1, 1)
42
```

I will write add this into the contribution guidelines and also add the followng linters `flake8-docstrings`,
`flake8-rst-docstrings` and `flake8-sphinx-links` to out test suite.

**Comment by jwa7** [comment]
Is there something special we need to consider with the render tag before the docstring? 

For instance:
```py
def func():
    r"""
    ...
    """
    # Code
    return
```

**Comment by PicoCentauri** [comment]
You will need the raw string `r` in front of a docstring once you have math to avoid that `\` are interpreted. Without the `r` a pattern like `\n` results in a new line, but especially with latex commands this will lead to errors.
