### ISSUE TITLE
Labels for `center_species` and `neighbor_species` should be chemical symbols not atomic numbers

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/equistore#15]
Descriptor labels (at least for SOAP and LODE), labeling different blocks currently are tuples of integers: `('spherical_harmonics_l', 'center_species', 'neighbor_species'), where a species label is the atomic number of the corresponding species.

To distinguish the spherical harmonic label (clearly integers) from species labels, I suggest using strings of chemical symbols for the two species labels on the user-facing side. Tuples of an integer and two strings make label interpretation and selection much easier for new users. Internally, one can map these to integers again.

**Comment by PicoCentauri** [comment]
I also see the point of diverging API's and the problem of typed languages. 

But, most of the "users" will apply the Python interface for their problems and especially do their prototyping in Python. Maybe later they port their code to Rust, C etc. For the transition from Python replacing strings to integers is nasty but acceptable. I could imagine a Python API (Allowing strings and integers) while only integers are allowed for rust and c. The benefits of usability in Python could overcome the lack of performance we get from casting. Python is slow anyway and additionally people writing C or Rust code are used to pain :)

**Comment by ceriottm** [comment]
Hi all, TBH I don't think this is such a huge improvement in usability -
not one that justifies substantial performance penalties, or making the
library much more complicated. One could have some utilities, Python side,
that convert strings to ints so if you can do elementid("H") or something
like that.

**Comment by PicoCentauri** [comment]
For sure I also don't want to introduce any performance penalties. We can leave this issue open, wait and see how this is being and adapted by the users. If everybody is introducing boilerplate code mapping the atomic numbers to chemical symbols we can think putting it into directly into the library itself.

**Comment by Luthaf** [comment]
Let's close this for now, this would require pretty fundamental changes to the code for limited advantage.
