### ISSUE TITLE
Importing `equistore.io` automatically, and perhaps a rename?

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/equistore#154]
**Importing**

I notice that these functions aren't automatically loaded, i.e. you can't do:

```py
import equistore
equistore.io.load(...)
>>>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'equistore' has no attribute 'io'
```
you have to do:
```py
import equistore.io
equistore.io.load(...)
```

Having it imported would be consistent with the new importing convention, with qualified names for functions, explicit imports for classes, i.e. from @Luthaf 's suggestion:

```py
import equistore
from equistore import TensorMap, TensorBlock, Labels

def func(...) -> TensorMap:
    pass

a = TensorBlock(...)
b = TensorMap(...)

c = equistore.function(a, b)
```

**A rename?**

In a similar vein to numpy and torch, should we just have `equistore.save` and `equistore.load` instead of `equistore.io.save` and `equistore.io.load`?

**Comment by Luthaf** [comment]
Yeah, it is a bit silly that you have to import `equistore.io` separately. I would be fine with either renaming (especially now that we also import operations in the root) or automatic import.

**Comment by PicoCentauri** [comment]
I also like `equistore.save` and `equistore.load`. You want to do it @jwa7 ?

**Comment by jwa7** [comment]
Sure happy to do it
