### ISSUE TITLE
Introduce a `drop_blocks` operation

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/equistore#168]
As mentioned in issue #145 , an equistore operation that drop blocks from a TensorMap by their key name would be useful.I already have a working prototype function, but it is currently untested: 

```py
def drop_blocks(tensor: TensorMap, keys: Labels) -> TensorMap:
    """
    Drop specified key/block pairs from a TensorMap.

    :param tensor: the TensorMap to drop the key-block pair from.
    :param keys: a :py:class:`Labels` object containing the keys of the 
        blocks to drop

    :return: the input :py:class:`TensorMap` with the specified key/block 
        pairs dropped.
    """
    if not np.all(tensor.keys.names == keys.names):
        raise ValueError(
            "The input tensor's keys must have the same names as the specified"
            + f" keys to drop. Should be {tensor.keys.names} but got {keys.names}"
        )
    new_keys = tensor.keys[tensor.keys != keys]
    return TensorMap(keys=new_keys, blocks=[tensor[key].copy() for key in new_keys])
```

I'm tagging this as a `good first issue` because it is a simple function that should be fairly simple to write unit tests for. Tests should check that all the appropriate keys in the output TensorMap are there, and the ones requested to be dropped are not. Then, the metadata and data of each block still present should be checked again the original TensorMap, including gradients.

**Comment by Luthaf** [comment]
> But do also we want something where like you give one key_names and a value and the function drop all the block with that value for the key_name

We can take this a bit further: give m names and corresponding values, and drop all matching keys/blocks (assuming the keys have n>=m names). This would select which keys to drop with the same algorithm already used for sample/feature selection in rascaline. A function to help with this is also discussed there: https://github.com/lab-cosmo/equistore/issues/97#issuecomment-1398635606

**Comment by jwa7** [comment]
Yes these are good ideas
