### ISSUE TITLE
Link source code in the documentation

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/equistore#171]
We had recently discussion about increasing code contribution and a feature that motivates me a lot to look more into the code (and to potentially contribute code) is a link to the source code in the doc.
For example like the `[SOURCE]` link here https://pytorch.org/docs/stable/generated/torch.nn.Linear.htmlhttps://pytorch.org/docs/stable/generated/torch.nn.Linear.html

**Comment by PicoCentauri** [comment]
Yes, very good idea. `sphinx.ext.viewcode` can do this as far as I know. It should be a simple addition here:

https://github.com/lab-cosmo/equistore/blob/a1e62e1edebd3ca444357b897bc4de82cf7fb561/docs/src/conf.py#L59-L62

**Comment by Luthaf** [comment]
Fixed by #184
