### ISSUE TITLE
Accessing blocks in empty tensor map

### ISSUE THREAD

**Issue by cbenmahm** [lab-cosmo/equistore#174]
Hey! I think this is a bug. I am able to create an empty tensor map, but then I am not allowed to access the blocks as the code raises a ValueError `ValueError: Couldn't find any block matching the selection {}`

Snippet to reproduce the bug

```py
empty_tensor = TensorMap(keys=Labels.empty("key"), blocks=[])
empty_tensor.blocks()
```

**Comment by jwa7** [comment]
Thanks @cbenmahm ! Perhaps calling `empty_tensor.blocks()` as above should return an empty list `[]`. 

But then there is a question for the general case. If we have a non-empty tensor, and call the `blocks()` method whilst trying to select a keys that don't exist - i.e. `tensor.blocks(sphercal_harmonics_l=-1, species_center=1)`, should this raise the same error as above, or return an empty list too?

**Comment by Luthaf** [comment]
> If we have a non-empty tensor, and call the blocks() method whilst trying to select a keys that don't exist

I prefer raising an error, to indicate typos and such as soon as possible to users. Otherwise they could spend a lot of time trying to debug this kind of issues
