### ISSUE TITLE
unexpected behavior when comparing two TensorBlocks

### ISSUE THREAD

**Issue by cbenmahm** [lab-cosmo/equistore#177]
Using `==` to compare two identical blocks yields False, while using `equistore.equal_block` gives True

snippet to recreate the bug:
`equistore.equal_block(tensor[key], tensor[key]), tensor[key] == tensor[key]`

**Comment by cbenmahm** [comment]
this is yesterday's newa

**Comment by Luthaf** [comment]
For reference, @cbenmahm was using an "old" version (from yesterday) missing the changes from #141
