### ISSUE TITLE
Remove `component_to_properties`

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/equistore#190]
This function main use case was to compare the spherical expansion values created by rascaline with librascal. I don't think it has any other use case, so I would suggest removing it. If you are using it for any reason, please tell us here!

**Comment by DavideTisi** [comment]
i was using it to get a 1d array to multiply stuff together, I can do it in other ways for sure

**Comment by DavideTisi** [comment]
i am using in the LiPS gamma-beta steering i was telling at the GM

**Comment by ceriottm** [comment]
I think it can be useful to drop equivariant behavior. For instance if one wants to use the density coefficients ignoring the covariant behavior. I believe @davidetisi and I are using it in the metadynamics project

**Comment by Luthaf** [comment]
Fair enough. I've got a couple of people asking me for a `component_to_samples` as well, and for completness it feels like we should also have `sample_to_component`, `property_to_component` and `reorder_components`.

**Comment by Luthaf** [comment]
Tracking the new functions in #284
