### ISSUE TITLE
Check that operations do not modify the input tensors in-place

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/equistore#207]
Following on from the issue raised in #206, I am opening this issue to ensure all operations are checked for in-place modifications, and unit tests are updated to catch such errors.

For the unit tests for every operation, add a simple `assert equistore.equal(tensor, tensor)` after the `tensor` has been used in an operation to ensure that it has not been modified by that operation. This is a simple but very important test, as in-place modifications of TensorMaps can break an entire workflow.

**Comment by Luthaf** [comment]
> For the unit tests for every operation, add a simple assert equistore.equal(tensor, tensor) after the tensor has been used in an operation to ensure that it has not been modified by that operation. 

I don't see how that helps: even if `tensor` has been modified in-place, it is still equal to itself. We could make a copy before the operation and check the tensor after the operation against the copy before though.


---

(I removed the bug label, this is not an issue about a specific bug, but about how to prevent some of them)

**Comment by jwa7** [comment]
Closed by issue #212 and PR #208
