### ISSUE TITLE
Bug in equistore.allclose()

### ISSUE THREAD

**Issue by arthur-lin1027** [lab-cosmo/equistore#294]
I don't think the new API changes in equistore were reflected in the logic suite, and when I ran `equistore.allclose(tensor_1, tensor_2)`, I got an error because looping through a tensor_map no longer yields a (key,block) pair.
```python
  for key, block_1 in tensor_1:
      try:
          allclose_block_raise(
              block_1,
              tensor_2.block(key),
              rtol=rtol,
              atol=atol,
              equal_nan=equal_nan,
          )
      except NotEqualError as e:
          raise NotEqualError(f"blocks for key '{key}' are different") from e

```
This is an easy fix:
* make these for loops loop through `tensor.items()` rather than tensor
* Improve code coverage in the docstring so that we actually hit this case -- the docstring didn't test for two equal tensorblocks which is why this error was not caught
* Propagate these changes through to the rest of the logic functions

**Comment by Luthaf** [comment]
The origin of this issue was an out-of-date version of equistore-operations.
