### ISSUE TITLE
`keys_to_properties` and `keys_to_samples` move Labels dimensions inconsistently

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/equistore#300]
When calling `keys_to_samples` and `keys_to_properties`  on the same key's name of a `TensorMap`, the new sample is inserted at the end of the `samples` dimension while the new `property` is located in the first column:

```python
import numpy as np
import equistore

values = np.array([[1, 2], [3, 4]])
block = equistore.block_from_array(values)
keys = equistore.Labels(["keys", "extra"], np.array([[0, 0]]))
tensor = equistore.TensorMap(keys=keys, blocks=[block])

print(tensor.keys_to_properties("extra")[0])

print(tensor.keys_to_samples("extra")[0])
```

```
TensorBlock
    samples (2): ['sample']
    components (): []
    properties (2): ['extra', 'property']
    gradients: None
TensorBlock
    samples (2): ['sample', 'extra']
    components (): []
    properties (2): ['property']
    gradients: None
```

This seems inconsistently but maybe this is intended behavior?

**Comment by Luthaf** [comment]
This is indeed the intended behavior, and documented as such! The initial justification for it was the use case in rascaline: when moving something like `species_center` to the samples, we want to keep `structure` and `center` first in the sample dimensions; while for properties, it does not matter as much where we put the sample, but putting them first allow for larger chunks of the data to be moved from the old array to the new array, which improves performance.

**Comment by PicoCentauri** [comment]
Okay I see. Should we add this explanation to the docs? I was reading that it is like this but without explenation is seems like an inconsistently.

**Comment by Luthaf** [comment]
We could add a note somewhere, but I would not make this too prominent in the user docs (these functions' documentation are already quite complex …)

**Comment by PicoCentauri** [comment]
I am also fine with keeping it. We have this issue here if someone have the same problem.
