### ISSUE TITLE
Inconsistence output from `keys_to_properties`

### ISSUE THREAD

**Issue by seungbo-com** [lab-cosmo/equistore#311]
Hello, I had this issue a couple of months ago but didn't revise it since I wasn't using it for a while.
Sorry for this late question about this feature, which might not be a major issue now.

I have a problem with different outputs using the function `keys_to_properties`.
The TensorMap that I created is down below.

```
equistore.Labels(['species_center'], np.asarray([[14]], dtype=np.int32) )
calculator = rascaline.SoapPowerSpectrum(**hypers)
rho2i = calculator.compute(frames)    
rho2i.block

Output :
<bound method TensorMap.block of TensorMap with 6 blocks
keys: ['species_center' 'species_neighbor_1' 'species_neighbor_2']
              8                 8                   8
              8                 8                  14
              8                14                  14
             14                 8                   8
             14                 8                  14
             14                14                  14>
```

Before, I didn't have to specify a new TensorMap after applying the function for recalling the TensorMap with merged blocks.

```
rho2i.keys_to_properties(['species_neighbor_1', 'species_neighbor_2'])

Output:
TensorMap with 2 blocks
keys: ['species_center']
              8
             14
```
When I called the `TensorMap` 'rho2i', it gives modified ones, and each block contained 

- (8,8,8), (8,8,14), (8,14,14)
- (14,8,8), (14,8,14), (14,14,14)

But now, if I recall the `TensorMap`, it gives the original (Map with 6 blocks) `TensorMap`, which never happened before.
Unless I specify the modified one, it will bring back before it is edited.
I wanted to know if there were any changes to the function.

**Comment by DavideTisi** [comment]
Hi,
Not sure I understood your problem but if you were using an old version of equistore.
`keys_to_properties` used to modify in place the `TensorMap`. Since #86 it return a new `TensorMap`


```# before
tensor = ...
tensor.keys_to_properties("species_neighbor")

# now
tensor = ...
tensor = tensor.keys_to_properties("species_neighbor")```

**Comment by seungbo-com** [comment]
Thank you for the comment and sorry for the confusion from the former question.

Yes, I believe that is the issue that I'm having.
And it also matches the time, Dec 2022, when I used the old version of Equistore. 
Thank you for the information.
