### ISSUE TITLE
Segmentation fault when accessing TensorBlock that doesn't exist

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/equistore#58]
This bug was discovered when working through the notebook `tutorial-equivariant-models.ipynb` in the lab-cosmo/equistore-examples repo. I have included some MWE code below to illustrate the bug. This code should be executed in the relative directory `equistore-examples/` as it depends on an example water dataset found in the `equistore-examples/data/` directory.

**Set Up**

The dataset is loaded, hypers defined, and descriptors computed. Then, we can access a block of desired angular momentum, species center, and species neighbour as follows:
```
import ase.io
import equistore
from rascaline import SphericalExpansion

frames = ase.io.read("data/chemrev_nuprime-theta-grid_computed.xyz", ":")

hypers = {
    "cutoff": 2.0,
    "max_radial": 6,
    "max_angular": 4,
    "atomic_gaussian_width": 0.2,
    "radial_basis": {"Gto": {}},
    "cutoff_function": {"ShiftedCosine": {"width": 0.5}},
    "center_atom_weight": 1.0,
}

calculator = SphericalExpansion(**hypers)
descriptor = calculator.compute(frames, gradients=['positions'])

# Define block with l=2, center=O, neighbour=H
block1 = descriptor.block(spherical_harmonics_l=2,species_center=8,species_neighbor=1)
```

If we want to move the `species_neighbour` index from keys to properties, we can do so with the `key_to_properties()` function:

```
# Move the index from keys to properties
descriptor.keys_to_properties('species_neighbor')
```

**Expected Behaviour**

Because `species_neighbour` is no longer a valid key, we cannot define a block as above with the specification of `species_neighbour`. Doing so throws an error, as expected and desired:
```
# Define block with l=2, center=O, and invalid parameter neighbour=H
block2 = descriptor.block(spherical_harmonics_l=2,species_center=8,species_neighbor=1)

>>> EquistoreError: invalid parameter: 'species_neighbor' is not part of the keys for this tensor
```

Instead, a block must be accessed only by specifying the remaining valid keys:
```
block2 = descriptor.block(spherical_harmonics_l=2,species_center=8)
```

**Unexpected Behaviour**

If a block is defined, i.e. `block1`, and then its index is moved from keys to properties (as shown above), the block previously assigned to the variable `block1` no longer exists. If attempts are made to access this block, instead of an error being thrown a Segmentation Fault occurs at runtime and, if executing the code in a notebook, this result in the kernel dying.
```
# Define block with l=2, center=O, neighbour=H
block1 = descriptor.block(spherical_harmonics_l=2,species_center=8,species_neighbor=1)

# Move the index from keys to properties
descriptor.keys_to_properties('species_neighbor')

# Try to access block
block1

# >>> Kernel dies due to segmentation fault
```

Ideally, such user behaviour should result in a well-reported error as opposed to a runtime fault.

**Comment by Luthaf** [comment]
After discussing this, the simplest solution would be to make the TensorMap objects immutable as well, and have `keys_to_xxx` functions return new TensorMap objects. 

Given that we need to allocate new memory for the updated labels and data arrays anyway, making TensorMap immutable would not use more memory than the current API, as long as the user do not hold on blocks/values from inside the initial TensorMap.
