### ISSUE TITLE
Join function for two `TensorMap`s

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/equistore#62]
With LODE I have intensive calculations to perform. This requires pre-computing and saving the TensorMaps to quickly play around with some models based on the pre-computed values. To use as much as possible computer power I split my dataset into many chunks. After pre-computing these chunks, it would be nice to _join_ the individual TensorMaps into one for convenient model training.

However, AFAIK equistore is currently missing such a `join` function merging two TensorMaps into a new object. Below is a minimal example in Python of the user facing API.

```python
import ase.io
import equistore
from rascaline import SphericalExpansion

frames = ase.io.load("dataset.xyz")

calculator = SoapPowerSpectrum(
    cutoff=3.0,
    max_radial=6,
    max_angular=4,
    atomic_gaussian_width=0.3,
    center_atom_weight=1.0,
    radial_basis={"Gto": {},},
    cutoff_function={"ShiftedCosine": {"width": 0.5},}
)

descriptor_1 = calculator.compute(frames[:len(frames)//2])
descriptor_2 = calculator.compute(frames[len(frames)//2:])

# define a join function, that joins two TensorMaps
descriptor = equistore.join(descriptor_1, descriptor_2)

# Overload the `+` operator and allow
descriptor = descriptor_1 + descriptor_2
```

Pinging @DivyaSuman14  and @jwa7 since they were part of the discussion.

**Comment by jwa7** [comment]
Apologies, it looks like this solution already exists! See a34fc97

**Comment by ceriottm** [comment]
Yeah, but this is a hacky solution, so I'm all in favor of a cleaner
implementation of both join and slice.

**Comment by Luthaf** [comment]
So similarly to numpy's vstack and hstack, we would need two such `join` function. One `join_along_samples` (a.k.a. vstack), and one `join_along_properties` (a.k.a. hstack). Both could be implemented in Rust with function we already have on `eqs_array_t`.

**Comment by ceriottm** [comment]
Don't we also need one to join the blocks?
