### ISSUE TITLE
`Labels` object should have a sliceable `values` attribute of type np.ndarray

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/equistore#63]
**Current Behaviour**

When creating a `Labels` object, the user needs to pass both `names` and `values` as parameters.

```py
import numpy as np

from equistore import Labels

a = Labels(names=('structure', 'atom'), values=np.array([(0, 1), (0, 6), (0, 7), (0, 8), (0, 9)]))
```

If we want to reaccess the names, it is as simple as calling:
```py
a.names
>>> ('structure', 'atom')
```
which returns the tuple we passed as a parameter when creating the object. 

However, in order to access the `values` we passed, we must call `a.asarray()` in order to receive a sliceable numpy array.
```py
# No 'values' attribute
a.values
>>> AttributeError: 'Labels' object has no attribute 'values'

# Sliceable Array
a.asarray()[:,1]
>>> Labels([1, 6, 7, 8, 9], dtype=int32)
```

**Proposed Behaviour**

I think it would make more sense to be able to have an attribute `Labels.values`, consistent with the name of the parameter used to instantiate the `Labels` object, that returns a sliceable array, such as:
```py
a.values[:,1]
>>> Labels([1, 6, 7, 8, 9], dtype=int32)
```
This would be more intuitive for the un-familiar user and not require (in my experience at least) searching through the attributes of the `Label` object for the one that would return me a sliceable array - such as trying but failing to slice or get relevant values from `a`, `a.base`, `a.data`, or having to manipulate the objects returned by them to make them sliceable.

**Comment by Luthaf** [comment]
I think changing the API of Labels will be required for the TorchScript version of equistore. In TorchScript, we will only have access to torch Tensor, and these do not support the numpy [structured arrays](https://numpy.org/doc/stable/user/basics.rec.html#structured-arrays) we are currently using. 

So we might have to provide a separate `values` field in TorchScript, and so for consistency do the same in the default Python bindings. We could still provide the right `__getitem__` implementation to enable things like this:

```py
labels = Label(["structure", "center", "neighbor"], values=...)

labels["structure"] == values[:, 0]
labels[["structure", "neighbor"]] == values[:, [0, 2]]
```
