### ISSUE TITLE
Create a utility function to convert ``TensorMap`` block values to type ``torch.tensor``

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/equistore#70]
In order to be compatible as input to PyTorch models, the ``TensorBlock.values`` tensors in each block of a ``TensorMap`` need to be of type ``torch.tensor``, instead of a ndarray, i.e. ``numpy.ndarray`` or ``_RustNDArray``.

**Desired Behaviour**

There should be a utility function accessible through the Python API, perhaps in a new file such as _equistore/python/src/equistore/operations/tensormap_to_torch.py_, that is used in the following way:
```py
new_tensormap = tensormap_to_torch(tensormap)
```

**Implications**

This necessarily has to be implemented as part of the Python API as there is no Rust-side solution to creating ``torch.tensor`` objects. This means that the above function ``tensormap_to_torch()`` will have to return a new ``TensorMap`` object, thus creating a copy of the object in memory. However, doing it this way round means that all the infrastructure that builds descriptors need not be written to be compatible with PyTorch; only at the step before building a model do we need to convert our blocks to ``torch.tensor`` objects.

**Comment by ceriottm** [comment]
I would implement it to be as similar as possible to how one would use this
on torch/numpy. So we could have for both `TensorBlock` and `TensorMap`
from_numpy() and from_torch() functions.

**Comment by jwa7** [comment]
Do you mean like this:

```py
new_torch_based_tensormap = tensormap_from_numpy(numpy_based_tensormap)
```

and 

```py
new_numpy_based_tensormap = tensormap_from_torch(torch_based_tensormap)
```

where under the hood ``tensormap_from_numpy()`` and ``tensormap_from_torch()``  iterate over blocks and call ``tensorblock_from_numpy()`` and ``tensorblock_from_torch()`` functions, respectively?

**Comment by ceriottm** [comment]
Yes, but I was thinking of mimicking more closely torch, that has a
`torch.from_numpy` call.
anyway, let's implement the functions, and then talk about their name.
M

**Comment by Luthaf** [comment]
The issue with `torch.from_numpy` is that we don't know what the output format should be. What would `TensorMap.from_numpy` create? Torch tensors, JAX arrays, ...? 

If we want to prevent proliferation of function, we could have `convert_tensormap(tensormap, backend="torch", device=..., dtype=...)` or similar.

**Comment by ceriottm** [comment]
I like the solution of a `equistore.backend_convert` function that can be applied to any object and make it compatible with the desired memory handler.
