### ISSUE TITLE
Counterintuitive parameters for `sum_over_samples`

### ISSUE THREAD

**Issue by ceriottm** [lab-cosmo/equistore#90]
Perhaps it's just me, but I find the syntax for sum/mean over samples to be very confusing. 
If I have a function `sum_over_samples` with a parameter `sample_names` I would expect it to sum over the indices given by `sample_names` - instead effectively it sums over all other indices "gathering" by `sample_names`. 

Perhaps calling the argument `reduced_samples` would be enough, but IMO - in analogy with what numpy does for `sum` and `mean` where you specify with `axis` the axis to sum over - I would keep the name but change the logic so you specify the sample names to sum over, and it matches all the others. 

Thoughts?

**Comment by Luthaf** [comment]
Ping @DavideTisi as well, since he implemented this in #74.

---

We could also rename the parameter to `group_by`, giving us 

```py
tensor = ...
equistore.operations.sum_over_samples(tensor, group_by=["structure"])
```

as a side note, we should support passing a single string instead of a list with a single element, i.e.

```py
tensor = ...
equistore.operations.sum_over_samples(tensor, group_by="structure")
```

**Comment by DavideTisi** [comment]
The naming can be of course changed, it is fine for me, I understand why it can be confusing. @Luthaf's idea of `group_by` works for me. 

I do not like very much supporting a single string, the idea of the function is to group all the lines with the same values for the sample in the list `sample_names`, using only a string, in my opinion, hides a bit that you can use more than one. I understand that one can read the doc to see all the things that can be done but I find forcing the user to use the list more explicit. Of course, changing the function to support the string can be done, if you have the feeling that it is better.

**Comment by jwa7** [comment]
I think the ``group_by`` arg works, and also agree with Guillaume that it would be useful UX wise to have the option of passing both a list and a string.

On a separate note, just a comment on _reduce_over_samples.py__ and the redundancy in it. It looks like fxns ``sum_over_samples`` and ``mean_over_samples`` are exactly equivalent except in the ``reduction="sum"`` or ``reduction="mean"`` argument to the ``_reduce_over_samples_block`` fxn call. Would it be appropriate to define a private fxn on the ``TensorMap`` level, called perhaps ``_reduce_over_samples`` or ``_reduce_over_samples_tensor`` that code wise looks exactly like ``sum_over_samples`` and ``mean_over_samples`` but takes the reduction string as an argument too? This way the 2 user facing fxns ``sum_over_samples`` and ``mean_over_samples`` would just call ``_reduce_over_samples`` with different respective reduction strings.

For instance:
```py
def _reduce_over_samples_block(
    block: TensorBlock, group_by: Union[List[str], str], reduction: str
) -> TensorBlock:
    ...

def _reduce_over_samples(tensor: TensorMap, group_by: Union[List[str], str], reduction: str) -> TensorMap:
    """Create a new :py:class:`TensorMap` with the same keys as
    as the input ``tensor``, and each :py:class:`TensorBlock` is obtained
    summing the corresponding input :py:class:`TensorBlock` over the rows with
    the same ``group_by`` sample names. 

    Both "sum" and "mean" reductions can be performed.

    For example if ``group_by = "structure"``, the function reduces over all
    the sample with the same structure, and if ``group_by = ["structure",
    "center"]`` it sums over all the rows with the same values for both
    ``"structure"`` and ``"center"`` samples.

    :param tensor: input :py:class:`TensorMap`
    :param group_by: names of samples to reduce over
    :param reduction: how to reduce, i.e. with "mean" or "sum"
    """
    if isinstance(group_by, str):
        group_by = [group_by]
    # We check that the names in sample_names are indeed presents in the block
    for sample in group_by:
        if sample not in tensor.sample_names:
            raise ValueError(
                f"one of the requested sample name ({sample}) is not part of "
                "this TensorMap"
            )

    blocks = []
    for _, block in tensor:
        blocks.append(
            _reduce_over_samples_block(
                block=block,
                group_by=group_by,
                reduction=reduction,
            )
        )
    return TensorMap(tensor.keys, blocks)

def mean_over_samples(tensor: TensorMap, group_by: Union[List[str], str]) -> TensorMap:
    """Create a new :py:class:`TensorMap` with the same keys as
    as the input ``tensor``, and each :py:class:`TensorBlock` is obtained
    averaging the corresponding input :py:class:`TensorBlock` over the rows with
    the same ``group_by``.

    For example if ``group_by = "structure"``, the function averages over
    all the sample with the same structure, and if ``group_by = ["structure",
    "center"]`` it averages over all the rows with the same values for both
    ``"structure"`` and ``"center"`` samples.

    :param tensor: input :py:class:`TensorMap`
    :param group_by: names of samples to average over
    """
    return _reduce_over_samples(tensor, group_by, reduction="mean")

def sum_over_samples(tensor: TensorMap, group_by: Union[List[str], str]) -> TensorMap:
    """Create a new :py:class:`TensorMap` with the same keys as
    as the input ``tensor``, and each :py:class:`TensorBlock` is obtained
    summing the corresponding input :py:class:`TensorBlock` over the rows with
    the same ``group_by``.

    For example if ``group_by = "structure"``, the function sums over all
    the sample with the same structure, and if ``group_by = ["structure",
    "center"]`` it sums over all the rows with the same values for both
    ``"structure"`` and ``"center"`` samples.

    :param tensor: input :py:class:`TensorMap`
    :param group_by: names of samples to sum over
    """
    return _reduce_over_samples(tensor, group_by, reduction="sum")
```

**Comment by DavideTisi** [comment]
Yes, fine for me, i can do the PR later in the afternoon
